table hospital
	lineageTag: 770e5c6d-6af9-424b-abdb-b0e601d922d2

	measure AverageLengthOfStayByMedication = ```
			
			CALCULATE(
			    AVERAGE(Visit[LengthOfStay]),
			    VALUES(Medication[MedicationName])
			)
			
			```
		lineageTag: f571b648-9ab3-4120-9e7e-536ead9a685f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ShortestLengthOfStayMedication = ```
			
			MINX(
			    SUMMARIZE(
			        Medication,
			        Medication[MedicationName],
			        "AvgLengthOfStay", [AverageLengthOfStayByMedication]
			    ),
			    [AvgLengthOfStay]
			)
			
			```
		lineageTag: 12e5584d-7563-4a1c-8344-329a56e00e22

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AvgLengthOfStay = ```
			AVERAGE(Visit[LengthOfStay])
			
			```
		lineageTag: 4ed5ce16-65d0-4898-b996-ad5f2fad3f6d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalProcedures = ```
			COUNTROWS(Procedure)
			
			```
		formatString: 0
		lineageTag: 08421e1e-7372-45f9-8cd2-7568d229cdea

	measure TotalMedications = ```
			COUNTROWS(Medication)
			
			```
		formatString: 0
		lineageTag: 4afd007d-e082-4981-8519-a4af0c083220

	column HospitalID
		dataType: int64
		formatString: 0
		lineageTag: ed387a0e-f225-480b-ad49-e409df4e4659
		summarizeBy: none
		sourceColumn: HospitalID

		annotation SummarizationSetBy = Automatic

	column HospitalName
		dataType: string
		lineageTag: 48ff3209-670e-405c-8b70-cd490acc7555
		summarizeBy: none
		sourceColumn: HospitalName

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6fe51da9-bd89-4596-9eff-3d3514adefca
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Capacity
		dataType: int64
		formatString: 0
		lineageTag: 588fa720-2656-44f9-8f23-d8e7b8ef5301
		summarizeBy: none
		sourceColumn: Capacity

		annotation SummarizationSetBy = Automatic

	partition hospital = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\youni\Downloads\Health care\hospital.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"HospitalID", Int64.Type}, {"HospitalName", type text}, {"Region", type text}, {"Capacity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

