table medication
	lineageTag: a821d118-b0f3-40ca-9ff7-2052ac129083

	column MedicationID
		dataType: int64
		formatString: 0
		lineageTag: ee7702a9-ef76-4e8f-a5ce-640aa2724328
		summarizeBy: count
		sourceColumn: MedicationID

		annotation SummarizationSetBy = Automatic

	column VisitID
		dataType: int64
		formatString: 0
		lineageTag: 41b5d779-4df2-4478-84ae-5c111f529500
		summarizeBy: none
		sourceColumn: VisitID

		annotation SummarizationSetBy = Automatic

	column MedicationName
		dataType: string
		lineageTag: 99c1bd2e-513e-4618-a8c8-c850e00a6dc5
		summarizeBy: none
		sourceColumn: MedicationName

		annotation SummarizationSetBy = Automatic

	column Dosage
		dataType: string
		lineageTag: 87c55b56-2fb6-4b93-be66-e3b9b941ddeb
		summarizeBy: none
		sourceColumn: Dosage

		annotation SummarizationSetBy = Automatic

	column Frequency
		dataType: string
		lineageTag: f94822fd-af88-42dd-98b9-efbcc9bcbe4f
		summarizeBy: none
		sourceColumn: Frequency

		annotation SummarizationSetBy = Automatic

	partition medication = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\youni\Downloads\Health care\medication.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"MedicationID", Int64.Type}, {"VisitID", Int64.Type}, {"MedicationName", type text}, {"Dosage", type text}, {"Frequency", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

