table visit
	lineageTag: b3da56f1-21f7-4fb7-9545-02cc26144e79

	measure 'Total Readmissions' = ```
			
			COUNTX(
			    FILTER(Visit, Visit[DischargeStatus] = "Transferred"),
			    Visit[VisitID]
			)
			
			```
		formatString: 0
		lineageTag: 5c053d18-d626-47fc-9860-6d5eb3834285

	measure 'Readmission Rate (%)' = ```
			
			DIVIDE([Total Readmissions], COUNT(Visit[VisitID]), 0) * 100
			
			```
		lineageTag: 187566ac-b74a-4ff0-b427-6afbb348018d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Length of Stay' = ```
			
			AVERAGE(Visit[LengthOfStay])
			
			```
		lineageTag: 099418ad-060a-47a6-9e0b-1a270083b263

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Number of Procedures' = ```
			
			COUNTROWS(
			    RELATEDTABLE(Procedure)
			)
			
			```
		formatString: 0
		lineageTag: 361bec98-e324-47e3-b4ab-a9acadfff1c3

	measure 'Avg LOS by Procedure' = ```
			
			AVERAGEX(
			    FILTER(
			        Procedure, 
			        Procedure[ProcedureID] IN VALUES(Procedure[ProcedureID])
			    ), 
			    RELATED(Visit[LengthOfStay])
			)
			
			```
		lineageTag: eb589b0b-9251-4041-a55b-0f02cb1b1514

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure VisitProcedureSummary = ```
			
			SUMMARIZE(
			    Visit,
			    Visit[VisitID],
			    "LengthOfStay", AVERAGE(Visit[LengthOfStay]),
			    "NumberOfProcedures", CALCULATE(COUNTROWS(Procedure))
			)
			
			```
		lineageTag: ca121fdd-b553-4b24-bcf2-42a8fc3ae187

	column VisitID
		dataType: int64
		formatString: 0
		lineageTag: 6f2ed052-3020-475b-b526-4f8b7fcadfed
		summarizeBy: none
		sourceColumn: VisitID

		annotation SummarizationSetBy = Automatic

	column PatientID
		dataType: int64
		formatString: 0
		lineageTag: 999a4326-8926-463d-bb55-ca2510d0e0a0
		summarizeBy: none
		sourceColumn: PatientID

		annotation SummarizationSetBy = Automatic

	column HospitalID
		dataType: int64
		formatString: 0
		lineageTag: 08a09f0e-2580-46d7-99dd-8fa476f38592
		summarizeBy: none
		sourceColumn: HospitalID

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9dd1ba6f-12f2-4221-8216-b59714a654cb
		summarizeBy: none
		sourceColumn: VisitDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AdmissionType
		dataType: string
		lineageTag: 9f4691bc-a1f8-4713-92c5-b388d6a7b369
		summarizeBy: none
		sourceColumn: AdmissionType

		annotation SummarizationSetBy = Automatic

	column LengthOfStay
		dataType: int64
		formatString: 0
		lineageTag: bffb66de-0fd5-4daa-b5bb-235731f5896a
		summarizeBy: sum
		sourceColumn: LengthOfStay

		annotation SummarizationSetBy = Automatic

	column DischargeStatus
		dataType: string
		lineageTag: 0b9bdfb7-c5bf-4f44-9c37-9acfd23599ef
		summarizeBy: none
		sourceColumn: DischargeStatus

		annotation SummarizationSetBy = Automatic

	partition visit = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\youni\Downloads\Health care\visit.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"VisitID", Int64.Type}, {"PatientID", Int64.Type}, {"HospitalID", Int64.Type}, {"VisitDate", type date}, {"AdmissionType", type text}, {"LengthOfStay", Int64.Type}, {"DischargeStatus", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

