table MedicationSummary
	lineageTag: d6d06431-2993-4f71-a86d-2baa6ab45aed

	measure MedicationPercentage = ```
			
			DIVIDE(
			    COUNT(Medication[MedicationID]),
			    CALCULATE(COUNT(Medication[MedicationID]), ALL(Visit[AdmissionType]))
			) * 100
			
			```
		lineageTag: 32ee6dce-b97c-4ec8-bf38-75c1605f78b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AdmissionType
		lineageTag: 184fed7d-4c4e-4a44-b6e2-fcd963894f51
		summarizeBy: none
		isNameInferred
		sourceColumn: visit[AdmissionType]

		annotation SummarizationSetBy = Automatic

	column MedicationName
		lineageTag: 13bf6c70-908f-4ac2-a806-eb59b1da483a
		summarizeBy: none
		isNameInferred
		sourceColumn: medication[MedicationName]

		annotation SummarizationSetBy = Automatic

	column PrescriptionCount
		formatString: 0
		lineageTag: d8501719-58d8-450f-b25b-c1109c8b630b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [PrescriptionCount]

		annotation SummarizationSetBy = Automatic

	partition MedicationSummary = calculated
		mode: import
		source = ```
				
				SUMMARIZE(
				    Medication,
				    Visit[AdmissionType],
				    Medication[MedicationName],
				    "PrescriptionCount", COUNT(Medication[MedicationID])
				)
				
				```

	annotation PBI_Id = 94be12c80034417f88c0be949418ca37

