CREATE TABLE [dbo].[MP_leads] (

	[Engagement ID] varchar(8000) NULL, 
	[Referral ID] varchar(8000) NULL, 
	[Lead Name] varchar(8000) NULL, 
	[Customer Name] varchar(8000) NULL, 
	[Customer Address Line 1] varchar(8000) NULL, 
	[Customer Address Line 2] varchar(8000) NULL, 
	[Customer City] varchar(8000) NULL, 
	[Customer State] varchar(8000) NULL, 
	[Customer Postal Code] varchar(8000) NULL, 
	[Customer Country] varchar(8000) NULL, 
	[Customer D-U-N-S id] varchar(8000) NULL, 
	[Customer Contact First Name] varchar(8000) NULL, 
	[Customer Contact Last Name] varchar(8000) NULL, 
	[Customer Contact Phone number] varchar(8000) NULL, 
	[Phone Validity] varchar(8000) NULL, 
	[Customer Contact Email Address] varchar(8000) NULL, 
	[Email Validity] varchar(8000) NULL, 
	[Partner Referral Status] varchar(8000) NULL, 
	[Partner Referral Substatus] varchar(8000) NULL, 
	[Decline/Lost/Error reason] varchar(8000) NULL, 
	[Sales Stage] bigint NULL, 
	[Estimated Deal Value] varchar(8000) NULL, 
	[Currency] varchar(8000) NULL, 
	[Referral Program] varchar(8000) NULL, 
	[Lead source] varchar(8000) NULL, 
	[Call to action] varchar(8000) NULL, 
	[Lead quality] varchar(8000) NULL, 
	[Lead type] varchar(8000) NULL, 
	[CRM ID] varchar(8000) NULL, 
	[Marketing Campaign ID] varchar(8000) NULL, 
	[Notes] varchar(8000) NULL, 
	[MPN Id] bigint NULL, 
	[Lead Created Date] date NULL, 
	[Offer 1] varchar(8000) NULL
);