table PPC
	lineageTag: 88d1aad4-baaa-414f-b200-3ce5c1de40d6

	column Column1
		dataType: string
		lineageTag: fa852572-eb1e-4b5f-ab4d-879825702fc3
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: e5b89ce2-0557-4dd5-a57d-a4a3162cc863
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition PPC = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(Web.Contents("https://yavdain-my.sharepoint.com/personal/chinmay_dhal_yavda_in/Documents/Apps/Microsoft Power Query/Uploaded Files/creative mapping 1.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "PPC", Kind = "Sheet"]}[Data],
				  #"Changed Type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}}, "en-US")
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

