table SSI
	lineageTag: e766634d-dbf0-4523-ad7a-2a6b368d990e

	column Column1
		dataType: string
		lineageTag: a0742535-fe54-40db-a500-c1e185cdfc16
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 175cb9d1-4cb1-4478-aa63-36869949356b
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition SSI = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(Web.Contents("https://yavdain-my.sharepoint.com/personal/chinmay_dhal_yavda_in/Documents/Apps/Microsoft Power Query/Uploaded Files/creative mapping 1.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "SSI", Kind = "Sheet"]}[Data],
				  #"Changed Type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}}, "en-US")
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

